### PR TITLE
Release v27

### PR DESCRIPTION
**Pull request by JuiP**
@quozl @chimosky Please review and merge :)

### CODE REVIEW

**Comment by quozl** [comment]
https://github.com/sugarlabs/spirolaterals/blob/master/Spirolaterals.py#L8 is not GPLv2+

**Comment by JuiP** [comment]
Ohh, I reffered to the LICENSE file that was added in this repository; isn't that GPLv2 ?

**Comment by quozl** [comment]
Interesting, thanks.  The license of software is primarily determined by the words that follow the copyright.  What you've found is that a LICENSE file conflicts with what is said after the copyright.  So now you have _two_ problems.  :grin:

**Comment by JuiP** [comment]
@quozl @chimosky Resolved the license conflicts; PR ready for merge :)

**Comment by JuiP** [comment]
@chimosky ping

**Pull request merged**
